import Head from "next/head";
import styles from "../styles/Home.module.css";
import Reload from "../Features/Mongo/Components/Reload/Reload";

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MongoDB Reloader</title>
        <meta name="theme-color" content="royalblue"></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <Reload />
    </div>
  );
}
